name: CI develop

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Install Gradle
        run: |
          sudo apt update
          sudo apt install -y gradle

      - name: Build Project
        run: |
          ./gradlew build --continue



