name: pr-ci-pipeline

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop, release-*]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: ls -al

